services:
  - type: web
    name: dashboard-bets-core
    env: node
    buildCommand: "npm run render-build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      NODE_ENV: production
